---
- name: install apache
  yum:
    name: httpd
    state: latest

- name: start the service
  service:
    name: httpd
    state: started
    enabled: true

- name: allow the service from the firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  notify: restart firewall
    
- name: copy index file
  template:
    src: ./hostfile.j2
    dest: /var/www/html/index.html
  notify: restart httpd

- name: change the hostname
  ansible.builtin.hostname:
    name: student-ID-webserver1
  when: ansible_facts['nodename'] == "host1"

- name: change the hostname
  ansible.builtin.hostname:
    name: student-ID-webserver2
  when: ansible_facts['nodename'] == "host2" 
